spring:

  password_auth: "@dminDvx2025!@"
  backup_path: "/backups"

  inventory_path: "C:\\Users\\orkhan\\Desktop\\nms_server\\nms\\src\\main\\resources\\inventory\\devices_inventory.yml"
  inventory_log_path: "C:\\Users\\orkhan\\Desktop\\nms_server\\nms\\src\\main\\resources\\inventory\\devices_inventory.log"
  playbook_path: "some_path2"

  python_venv_path: "some_path"

  ansible:
    user: orxan.n
    password: 0Rx@n2o25!

  snmp:
    community: netadmin

  webflux:
    session:
      cookie:
        same-site: None
        secure: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/nms
    username: postgres
    password: orxan20052004
    pool:
      enabled: true
      initial-size: 5
      max-size: 20